/**
 * CLI Command: memorix init
 *
 * Interactive generator for memorix.yml configuration file.
 * Creates a project-level or user-level memorix.yml with guided prompts.
 */

import { defineCommand } from 'citty';
import * as p from '@clack/prompts';
import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { homedir } from 'node:os';

export default defineCommand({
  meta: {
    name: 'init',
    description: 'Initialize memorix.yml configuration',
  },
  args: {
    global: {
      type: 'boolean',
      description: 'Create user-level config (~/.memorix/memorix.yml) instead of project-level',
      required: false,
    },
  },
  run: async ({ args }) => {
    p.intro('Initialize Memorix Configuration');

    const isGlobal = !!args.global;
    const targetDir = isGlobal
      ? path.join(homedir(), '.memorix')
      : process.cwd();
    const targetPath = path.join(targetDir, 'memorix.yml');

    // Check for existing file
    if (existsSync(targetPath)) {
      const overwrite = await p.confirm({
        message: `${targetPath} already exists. Overwrite?`,
        initialValue: false,
      });
      if (p.isCancel(overwrite) || !overwrite) {
        p.outro('Cancelled.');
        return;
      }
    }

    // LLM config
    const llmProvider = await p.select({
      message: 'LLM provider (for smart dedup + fact extraction):',
      options: [
        { value: 'none', label: 'None', hint: 'free heuristic mode' },
        { value: 'openai', label: 'OpenAI', hint: 'gpt-4o-mini' },
        { value: 'anthropic', label: 'Anthropic', hint: 'claude-3-haiku' },
        { value: 'openrouter', label: 'OpenRouter', hint: 'multi-provider' },
        { value: 'custom', label: 'Custom', hint: 'OpenAI-compatible' },
      ],
    });
    if (p.isCancel(llmProvider)) { p.outro('Cancelled.'); return; }

    // Embedding config
    const embeddingProvider = await p.select({
      message: 'Embedding provider (for semantic search):',
      options: [
        { value: 'off', label: 'Off', hint: 'BM25 fulltext only' },
        { value: 'api', label: 'API', hint: 'OpenAI-compatible, best quality' },
        { value: 'fastembed', label: 'FastEmbed', hint: 'local ONNX' },
      ],
    });
    if (p.isCancel(embeddingProvider)) { p.outro('Cancelled.'); return; }

    // Git-Memory config
    const gitAutoHook = await p.confirm({
      message: 'Auto-install git post-commit hook for memory capture?',
      initialValue: false,
    });
    if (p.isCancel(gitAutoHook)) { p.outro('Cancelled.'); return; }

    // Behavior config
    const sessionInject = await p.select({
      message: 'Session start injection:',
      options: [
        { value: 'minimal', label: 'Minimal', hint: 'one-line hint (default)' },
        { value: 'full', label: 'Full', hint: 'inject top 5 memories' },
        { value: 'silent', label: 'Silent', hint: 'no injection' },
      ],
    });
    if (p.isCancel(sessionInject)) { p.outro('Cancelled.'); return; }

    // Build YAML content
    const lines: string[] = [
      '# memorix.yml — Memorix Platform Configuration',
      `# Generated by: memorix init${isGlobal ? ' --global' : ''}`,
      `# Date: ${new Date().toISOString().split('T')[0]}`,
      '',
    ];

    // LLM section
    if (llmProvider !== 'none') {
      lines.push('llm:');
      lines.push(`  provider: ${llmProvider === 'custom' ? 'openai' : llmProvider}`);
      if (llmProvider === 'openai') lines.push('  model: gpt-4o-mini');
      else if (llmProvider === 'anthropic') lines.push('  model: claude-3-haiku-20240307');
      lines.push('  # apiKey: sk-...  # Or set MEMORIX_LLM_API_KEY env var');
      if (llmProvider === 'custom') lines.push('  # baseUrl: http://localhost:11434/v1');
      lines.push('');
    }

    // Embedding section
    lines.push('embedding:');
    lines.push(`  provider: ${embeddingProvider}`);
    if (embeddingProvider === 'api') {
      lines.push('  # model: text-embedding-3-small');
      lines.push('  # apiKey: sk-...  # Or set MEMORIX_EMBEDDING_API_KEY env var');
    }
    lines.push('');

    // Git section
    lines.push('git:');
    lines.push(`  autoHook: ${gitAutoHook}`);
    lines.push('  ingestOnCommit: true');
    lines.push('  maxDiffSize: 500');
    lines.push('  skipMergeCommits: true');
    lines.push('');

    // Behavior section
    lines.push('behavior:');
    lines.push(`  sessionInject: ${sessionInject}`);
    lines.push('  syncAdvisory: true');
    lines.push('  autoCleanup: true');
    lines.push('  formationMode: active');
    lines.push('');

    // Server section
    lines.push('server:');
    lines.push('  transport: stdio');
    lines.push('  dashboard: true');
    lines.push('  dashboardPort: 3210');
    lines.push('');

    const content = lines.join('\n');

    // Write file
    mkdirSync(targetDir, { recursive: true });
    writeFileSync(targetPath, content, 'utf-8');

    p.log.success(`Created ${targetPath}`);
    p.log.info('Edit the file to add API keys and customize settings.');
    if (gitAutoHook) {
      p.log.info('Git post-commit hook will be auto-installed on next MCP server start.');
    }
    p.outro('Done! Restart your MCP server to apply.');
  },
});
